development:
  stripe_secret_key: 'sk_test_51IMEYICUwvbS0EU2aUK4HbCTJcg7HTHeKSrYpk4CPOqfrkDVBeVAG5vUWYDz0H89Hc9MbPS43aZl2LxZVcfW29Jm001sjSaATQ'
  stripe_publishable_key: 'pk_test_51IMEYICUwvbS0EU2uZK0YX2uHkLgEzagC9cF5UqxoJM3HWPxlK0zP2M7Mvj8FBl7hdvvU2kmIiTypqAVIwnfJr4F00eUmpyhQe'